#include "game.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#include "images/hogwarts.h"
#include "images/field.h"
#include "images/broom.h"
#include "images/bludger.h"
#include "images/snitch.h"

/* TODO: */
// Add any additional states you need for your app.
typedef enum {
  START,
  BACKTEXT,
  PLAY,
  WIN,
  LOSE,
} GBAState;

// checks if the broom collided with the bludger or snitch
int collided(int row1, int row2, int col1, int col2) {
    return (row1 < row2 + 15 && row1 + 15 > row2 && col1 < col2 + 15 && col1 + 15 > col2);
}

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial game state
  GBAState state = START;
  Broom b;
  // Bludger bl[2];
  Bludger bl;
  Snitch sn;


  while (1) {
    currentButtons = BUTTONS;  // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();


    switch (state) {
      case START:
        b.row = 10;
        b.col = 10;
        bl.row = 60;
        bl.col = 70;
       // for(int i = 0; i < 2; i++){
       //    bl[i].row = 60 + 40 * i;
       //    bl[i].col = 70 + 40 * i;
       //  }
        sn.row = 130;
        sn.col = 170;
        drawFullScreenImageDMA(hogwarts);
        //break;
        state = BACKTEXT;
      case BACKTEXT:
        drawString(20, 10, "WELCOME TO GAMEDAY AT HOGWARTS!", BLACK);
        drawString(40, 10, "PRESS START TO BEGIN", BLACK);
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = PLAY;
        }
        break;
      case PLAY:
        //buttons are in gba.h
        drawFullScreenImageDMA(field);
        drawImageDMA(b.row, b.col, BROOM_WIDTH, BROOM_HEIGHT, broom);
        drawImageDMA(sn.row, sn.col, SNITCH_WIDTH, SNITCH_HEIGHT, snitch);
        if(KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
        }
        if (KEY_DOWN(BUTTON_LEFT, currentButtons) && b.col > 0) {
          b.col -= 1;
        }
        if (KEY_DOWN(BUTTON_RIGHT, currentButtons) && b.col < WIDTH - 15) {
          b.col += 1;
        }
        if (KEY_DOWN(BUTTON_UP, currentButtons) && b.row > 0) {
          b.row -= 1; 
         }
        if (KEY_DOWN(BUTTON_DOWN, currentButtons) && b.row < HEIGHT - 15) {
          b.row += 1;
        }
        // for (int i = 0; i < 2; i++) {
        //   drawImageDMA(bl[i].row, bl[i].col, BLUDGER_WIDTH, BLUDGER_HEIGHT, bludger);
        // }
        drawImageDMA(bl.row, bl.col, BLUDGER_WIDTH, BLUDGER_HEIGHT, bludger);
        // if (collided(bl[0].row, b.row, bl[0].col, b.col) != 0) {
        //   state = LOSE;
        // }
        // if (collided(bl[1].row, b.row, bl[1].col, b.col) != 0) {
        //   state = LOSE;
        // }
        if (collided(bl.row, b.row, bl.col, b.col) != 0) {
          state = LOSE;
        }
        if (collided(sn.row, b.row, sn.col, b.col) != 0) {
          state = WIN;
        }
        break;
      // hits snitch
      case WIN:
        fillScreenDMA(GREEN);
        drawString(40, 50, "YOU FOUND THE SNITCH!", BLACK);
        drawString(60, 50, "YOU WIN", BLACK);
        drawString(110, 30, "HIT SELECT TO START OVER", BLACK);
        if(KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
        }
        break;
      // hits bludger
      case LOSE:
        fillScreenDMA(RED);
        drawString(40, 50, "YOU HIT A BLUDGER!", BLACK);
        drawString(60, 50, "YOU LOSE", BLACK);
        drawString(100, 50, "HIT SELECT TO START OVER", BLACK);
        if(KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          state = START;
        }
        break;
    }

    previousButtons = currentButtons;  // Store the current state of the buttons
  }

  UNUSED(previousButtons);  // You can remove this once previousButtons is used

  return 0;
}
